#!/bin/sh

ln -sf busybox ./bin/[
ln -sf busybox ./bin/ash
ln -sf busybox ./bin/basename
ln -sf busybox ./bin/bash
ln -sf busybox ./bin/cat
ln -sf busybox ./bin/chgrp
ln -sf busybox ./bin/chmod
ln -sf busybox ./bin/chown
ln -sf busybox ./bin/cp
ln -sf busybox ./bin/cut
ln -sf busybox ./bin/date
ln -sf busybox ./bin/dd
ln -sf busybox ./bin/df
ln -sf busybox ./bin/dirname
ln -sf busybox ./bin/dmesg
ln -sf busybox ./bin/dos2unix
ln -sf busybox ./bin/du
ln -sf busybox ./bin/dutmp
ln -sf busybox ./bin/echo
ln -sf busybox ./bin/false
ln -sf busybox ./bin/grep
ln -sf busybox ./bin/gunzip
ln -sf busybox ./bin/gzip
ln -sf busybox ./bin/head
ln -sf busybox ./bin/hostname
ln -sf busybox ./bin/kill
ln -sf busybox ./bin/ln
ln -sf busybox ./bin/ls
ln -sf busybox ./bin/mkdir
ln -sf busybox ./bin/mknod
ln -sf busybox ./bin/more
ln -sf busybox ./bin/mount
ln -sf busybox ./bin/mv
ln -sf busybox ./bin/pidof
ln -sf busybox ./bin/ping
ln -sf busybox ./bin/ps
ln -sf busybox ./bin/pwd
ln -sf busybox ./bin/reset
ln -sf busybox ./bin/rm
ln -sf busybox ./bin/rmdir
ln -sf busybox ./bin/sed
ln -sf busybox ./bin/sh
ln -sf busybox ./bin/sleep
ln -sf busybox ./bin/sort
ln -sf busybox ./bin/stty
ln -sf busybox ./bin/sync
ln -sf busybox ./bin/tar
ln -sf busybox ./bin/tee
ln -sf busybox ./bin/telnet
ln -sf busybox ./bin/test
ln -sf busybox ./bin/touch
ln -sf busybox ./bin/tr
ln -sf busybox ./bin/true
ln -sf busybox ./bin/umount
ln -sf busybox ./bin/uname
ln -sf busybox ./bin/uniq
ln -sf busybox ./bin/unix2dos
ln -sf busybox ./bin/zcat

ln -sf ../bin/busybox ./sbin/chroot
ln -sf ../bin/busybox ./sbin/ifconfig
ln -sf ../bin/busybox ./sbin/klogd
ln -sf ../bin/busybox ./sbin/loadkmap
ln -sf ../bin/busybox ./sbin/poweroff
ln -sf ../bin/busybox ./sbin/route
ln -sf ../bin/busybox ./sbin/syslogd
ln -sf ../bin/busybox ./sbin/telinit
ln -sf ../bin/busybox ./sbin/update

ln -sf sbin/init ./init
ln -sf halt ./sbin/reboot

ln -sf ../../bin/busybox ./usr/bin/chvt
ln -sf ../../bin/busybox ./usr/bin/clear
ln -sf ../../bin/busybox ./usr/bin/env
ln -sf ../../bin/busybox ./usr/bin/find
ln -sf ../../bin/busybox ./usr/bin/free
ln -sf ../../bin/busybox ./usr/bin/id
ln -sf ../../bin/busybox ./usr/bin/killall
ln -sf ../../bin/busybox ./usr/bin/logger
ln -sf ../../bin/busybox ./usr/bin/rdate
ln -sf ../../bin/busybox ./usr/bin/tail
ln -sf ../../bin/busybox ./usr/bin/touch
ln -sf ../../bin/busybox ./usr/bin/tty
ln -sf ../../bin/busybox ./usr/bin/wc
ln -sf ../../bin/busybox ./usr/bin/which
ln -sf ../../bin/busybox ./usr/bin/whoami
ln -sf ../../bin/busybox ./usr/bin/yes

ln -sf ae ./bin/vi

ln -sf ../sbin/route ./bin/route

ln -sf tinylogin ./bin/addgroup
ln -sf tinylogin ./bin/adduser
ln -sf tinylogin ./bin/delgroup
ln -sf tinylogin ./bin/deluser
ln -sf tinylogin ./bin/login
ln -sf tinylogin ./bin/su
ln -sf ../../bin/tinylogin ./usr/bin/passwd
ln -sf ../bin/tinylogin ./sbin/getty
ln -sf ../bin/tinylogin ./sbin/sulogin

# Init tree
ln -sf ../init.d/umountfs ./etc/rc0.d/S40umountfs
ln -sf ../init.d/netbase ./etc/rc0.d/K04netbase
ln -sf ../init.d/sendsigs ./etc/rc0.d/S20sendsigs
ln -sf ../init.d/sysklogd ./etc/rc0.d/K16sysklogd
ln -sf ../init.d/halt ./etc/rc0.d/S99halt
ln -sf ../init.d/urandom ./etc/rc0.d/S30urandom
ln -sf ../init.d/modutils ./etc/rc2.d/S20modutils
ln -sf ../init.d/network ./etc/rc2.d/S40network
ln -sf ../init.d/revoboot ./etc/rc2.d/S99revoboot
ln -sf ../init.d/rmnologin ./etc/rc2.d/S16rmnologin
ln -sf ../init.d/netbase ./etc/rc2.d/S03netbase
ln -sf ../init.d/sysklogd ./etc/rc2.d/S00sysklogd
ln -sf ../init.d/umountfs ./etc/rc6.d/S40umountfs
ln -sf ../init.d/netbase ./etc/rc6.d/K04netbase
ln -sf ../init.d/sendsigs ./etc/rc6.d/S20sendsigs
ln -sf ../init.d/sysklogd ./etc/rc6.d/K16sysklogd
ln -sf ../init.d/reboot ./etc/rc6.d/S99reboot
ln -sf ../init.d/urandom ./etc/rc6.d/S30urandom
ln -sf ../init.d/tz ./etc/rcS.d/S50tz
ln -sf ../init.d/dm ./etc/rcS.d/S60dm
ln -sf ../init.d/checkroot ./etc/rcS.d/S10checkroot
ln -sf ../init.d/bootmisc.sh ./etc/rcS.d/S55bootmisc
ln -sf ../init.d/mountall ./etc/rcS.d/S35mountall
ln -sf ../init.d/hostname ./etc/rcS.d/S40hostname

# LibC files
ln -sf libm-2.3.6.so ./lib/libm.so.6
ln -sf libnss_files-2.3.6.so ./lib/libnss_files.so.2
ln -sf libresolv-2.3.6.so ./lib/libresolv.so.2
ln -sf libnsl-2.3.6.so ./lib/libnsl.so.1
ln -sf libutil-2.3.6.so ./lib/libutil.so.1
ln -sf libcrypt-2.3.6.so ./lib/libcrypt.so.1
ln -sf ld-2.3.6.so ./lib/ld-linux.so.2
ln -sf libdl-2.3.6.so ./lib/libdl.so.2
ln -sf libnss_dns-2.3.6.so ./lib/libnss_dns.so.2
ln -sf libc-2.3.6.so ./lib/libc.so.6

# libPThread
ln -sf libpthread-0.10.so ./lib/libpthread.so.0

# Other stuff
ln -sf /tmp ./var/tmp

ln -sf nc ./usr/bin/netcat
ln -sf /usr/share/terminfo/ ./usr/lib/terminfo
