#!/bin/sh
# Set SULOGIN to yes if you want a sulogin to be spawned from
# this script *before anything else* with a timeout, like on SCO.
[ "$SULOGIN" = yes ] && sulogin -t 30 $CONSOLE

/bin/dmesg -n 1

# Mount /proc & /sys
mount -t proc /proc /proc
mount -t sysfs /sys /sys

# Go udev! Go!
mount -t tmpfs udev /dev
mknod -m 666 /dev/null c 1 3
mkdir -p /dev/.udev/db
udevd --daemon
udevadm trigger
udevadm settle

# Modify some kernel params
# write core files on the server
[ -f /proc/sys/kernel/core_pattern ] && echo "/revosave/core.%p.%e" >/proc/sys/kernel/core_pattern
[ -f /proc/sys/kernel/sysrq ] && echo "1" >/proc/sys/kernel/sysrq
