#!/bin/sh
# device mapper

. /usr/lib/revolib.sh

grep -q revorestore /proc/cmdline && exit 0

pretty_try "Scanning for LVM volumes"
lvm vgscan 2>/dev/null | logger
pretty_success
pretty_try "Activating LVM volumes"
lvm vgchange -ay 2>/dev/null | logger
pretty_success
