#!/bin/sh
#
# Modules loading
#

. /usr/lib/revolib.sh
PATH="/sbin:/bin:/usr/sbin:/usr/bin"

F=/etc/modules
if grep " revofull" /proc/cmdline
then
    F=/etc/modules.full
fi

# Loop over every line in /etc/modules.
pretty_try "Loading $F"
# make sure there is a LF at the end
cat $F |
while read module args
do
	case "$module" in
		\#*|"") continue ;;
	esac

	insmod /lib/modules/"$module".ko $args 2>/dev/null 1>/dev/null
done

# let the time for card init
sleep 2
pretty_success
exit

cat $F |
while read module args
do
	case "$module" in
		\#*|"") continue ;;
	esac

	if grep "^$module [0-9]\+ [0-9]*[1-9]\+ " /proc/modules -q
	then
	    pretty_blue "$module "
	fi

done
pretty_print "\n"
