#!/bin/sh

test -f /sbin/portmap || exit 0

case "$1" in
    start)
    #This really should not be done here.
echo -n "Starting base networking daemons:"
echo -n " portmap" ; start-stop-daemon --start --quiet --exec /sbin/portmap
echo "."
	;;
    stop)
	start-stop-daemon --stop --quiet --oknodo --exec /sbin/portmap
	;;
    reload)
	start-stop-daemon --stop --quiet --oknodo --pidfile /var/run/inetd.pid --signal 1 --exec /usr/sbin/inetd
	;;
    restart)
	pmap_dump >/var/run/portmap.state
	start-stop-daemon --stop --quiet --oknodo --exec /sbin/portmap
	start-stop-daemon --start --quiet --exec /sbin/portmap
	if [ -f /var/run/portmap.upgrade-state ]; then
	  pmap_set </var/run/portmap.upgrade-state
	elif [ -f /var/run/portmap.state ]; then
	  pmap_set </var/run/portmap.state
	fi
	rm -f /var/run/portmap.upgrade-state /var/run/portmap.state
	;;
    *)
	echo "Usage: /etc/init.d/netbase {start|stop|reload|restart}"
	exit 1
	;;
esac

exit 0
