#!/bin/sh

. /usr/lib/revolib.sh

test -f /sbin/portmap || exit 0

case "$1" in
    start)
    #This really should not be done here.
	pretty_try "Starting base networking daemons"
	if start-stop-daemon --start --quiet --exec /sbin/portmap
	then
	    pretty_success
	else
	    pretty_failure
	fi
	;;
    stop)
	start-stop-daemon --stop --quiet --oknodo --exec /sbin/portmap
	;;
    restart)
	pmap_dump >/var/run/portmap.state
	start-stop-daemon --stop --quiet --oknodo --exec /sbin/portmap
	start-stop-daemon --start --quiet --exec /sbin/portmap
	if [ -f /var/run/portmap.upgrade-state ]; then
	  pmap_set </var/run/portmap.upgrade-state
	elif [ -f /var/run/portmap.state ]; then
	  pmap_set </var/run/portmap.state
	fi
	rm -f /var/run/portmap.upgrade-state /var/run/portmap.state
	;;
    *)
	echo "Usage: /etc/init.d/netbase {start|stop|restart}"
	exit 1
	;;
esac

exit 0
