#!/bin/sh

. /usr/lib/revolib.sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
# Kill all processes.
pretty_info "Sending all processes the TERM signal"
killall5 -15

sleep 2

pretty_info "Sending all processes the KILL signal"
killall5 -9
