#!/bin/sh

. /usr/lib/revolib.sh

test -f /sbin/klogd || exit 0
test -f /sbin/syslogd || exit 0

# Options for start/restart the daemons
#   For remote UDP logging use SYSLOGD="-r"
#
SYSLOGD=""

#  Use KLOGD="-k /boot/System.map-$(uname -r)" to specify System.map
#
KLOGD=""

sleep 1
case "$1" in
  start)
    pretty_try "Starting system log daemon"
    if /sbin/syslogd $SYSLOGD
    then
	pretty_success
    else
	pretty_failure
    fi
    pretty_try "Starting kernel log daemon"
    if /sbin/klogd $KLOGD
    then
	pretty_success
    else
	pretty_failure
    fi
    ;;
  stop)
#    echo -n "Stopping system log daemon: klogd"
#    start-stop-daemon --stop --quiet --pidfile /var/run/klogd.pid
#    echo -n " syslogd"
#    start-stop-daemon --stop --quiet --pidfile /var/run/syslogd.pid
#    echo "."
    ;;
  *)
    echo "Usage: /etc/init.d/sysklogd {start|stop}"
    exit 1
esac
exit 0
