#!/bin/sh

. /usr/lib/revolib.sh

PATH=/sbin:/bin:/usr/sbin:/usr/bin
# Write a reboot record to /var/log/wtmp before unmounting

pretty_try "Deactivating LVM "
lvm vgchange -an 2>/dev/null
pretty_success

#echo -n "Deactivating swap... "
#swapoff -a
#echo "done."

pretty_try "Unmounting file systems "
umount -a
pretty_success
mount -n -o remount ro /
