--- Makefile.dist	2005-07-18 04:25:21.000000000 +0200
+++ Makefile	2009-08-27 15:48:05.747032684 +0200
@@ -1,5 +1,5 @@
 # Makefile for zlib
-# Copyright (C) 1995-2005 Jean-loup Gailly.
+# Copyright (C) 1995-2003 Jean-loup Gailly.
 # For conditions of distribution and use, see copyright notice in zlib.h

 # To compile and test, type:
@@ -16,16 +16,17 @@
 # To install in $HOME instead of /usr/local, use:
 #    make install prefix=$HOME

-CC=cc
+CC=gcc-3.4

-CFLAGS=-O
+#CFLAGS=-O
 #CFLAGS=-O -DMAX_WBITS=14 -DMAX_MEM_LEVEL=7
 #CFLAGS=-g -DDEBUG
-#CFLAGS=-O3 -Wall -Wwrite-strings -Wpointer-arith -Wconversion \
-#           -Wstrict-prototypes -Wmissing-prototypes
+CFLAGS=-O3 -Wall -Wwrite-strings -Wpointer-arith -Wconversion \
+           -Wstrict-prototypes -Wmissing-prototypes \
+           -DMAX_WBITS=14 -DMAX_MEM_LEVEL=7

 LDFLAGS=libz.a
-LDSHARED=$(CC)
+LDSHARED=$(CC) -shared
 CPP=$(CC) -E

 LIBS=libz.a
@@ -54,7 +55,9 @@

 TEST_OBJS = example.o minigzip.o

-all: example$(EXE) minigzip$(EXE)
+#all: example$(EXE) minigzip$(EXE)
+# we only need libz.a
+all: libz.a

 check: test
 test: all
@@ -78,7 +81,7 @@
 	rm -f _match.s

 $(SHAREDLIBV): $(OBJS)
-	$(LDSHARED) -o $@ $(OBJS)
+	$(LDSHARED) -o $@ $(OBJS) $(OBJA)
 	rm -f $(SHAREDLIB) $(SHAREDLIBM)
 	ln -s $@ $(SHAREDLIB)
 	ln -s $@ $(SHAREDLIBM)
