#!/bin/sh
#
# (c) 2003-2007 Linbox FAS, http://linbox.com
# (c) 2008-2009 Mandriva, http://www.mandriva.com
#
# $Id$
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
# Mount helper script
#

# get the mac address
getmac() {
    MAC=`cat /etc/shortmac`
}

# Get DHCP options
sed -e "s/Device/#/" -e "s/: */=/" -e "s/   //" -e "s/ /_/g" </etc/netinfo.log >/etc/netinfo.sh
. /etc/netinfo.sh

SIP=$Next_server
PREFIX=`dirname $Boot_file`
PREFIX=`dirname $PREFIX`
DIR=/lib/util/
if grep -q revosavedir /proc/cmdline ;then
    REVOSAVEDIR=`sed -e "s/.*revosavedir=\([^ ]*\).*/\1/" < /proc/cmdline`
fi

RPCINFO=`rpcinfo -p $SIP`

logger "rpcinfo:"
logger "$RPCINFO"

# check nfs
echo
sleep 1
if echo "$RPCINFO"|grep -q nfs
then
    echo "*** NFS seems to be ok on $SIP"
else
    echo "*** Warning : the NFS service does not seem to work on the LBS !"
fi

# get the short mac address
getmac

# Get NFS options
if grep -q slownfs /proc/cmdline
then
    NFSOPT=rsize=1024,wsize=1024,udp
else
    if echo "$RPCINFO"|grep nfs|grep -q tcp
    then
    NFSOPT=rsize=8192,wsize=8192,tcp
    else
    echo "*** No TCP on NFS server switching to UDP"
    NFSOPT=rsize=8192,wsize=8192,udp
    sleep 2
    fi
fi

if [ -z "$Option_177" ]
then
    echo "Using $SIP:$PREFIX as binaries dir"
    mount -t nfs $SIP:$PREFIX$DIR /opt -o hard,intr,nolock,$NFSOPT
    mount -t nfs $SIP:$PREFIX/images /revoinfo -o hard,intr,nolock,$NFSOPT
    [ -z $REVOSAVEDIR ] || mount -t nfs $SIP:$PREFIX$REVOSAVEDIR /revosave -o hard,intr,nolock,$NFSOPT
else
    echo "Using Option 177: $Option_177 as binaries dir"
    mount -t nfs $Option_177$DIR /opt -o hard,intr,nolock,$NFSOPT
    mount -t nfs $Option_177/images /revoinfo -o hard,intr,nolock,$NFSOPT
    [ -z $REVOSAVEDIR ] || mount -t nfs $Option_177$REVOSAVEDIR /revosave -o hard,intr,nolock,$NFSOPT
fi
# IMPORTANT !!! NO OTHER INSTRUCTIONS AFTER MOUNTS !!!
