#!/bin/sh
#
# (c) 2003-2007 Linbox FAS, http://linbox.com
# (c) 2008-2009 Mandriva, http://www.mandriva.com
#
# $Id$
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
# Mount helper script
#

# get the mac address
getmac() {
    MAC=`cat /etc/shortmac`
}

# Get DHCP options
sed -e "s/Device/#/" -e "s/: */=/" -e "s/   //" -e "s/ /_/g" </etc/netinfo.log >/etc/netinfo.sh
. /etc/netinfo.sh

SIP=$Next_server
PREFIX=`dirname $Boot_file`
PREFIX=`dirname $PREFIX`
SAVEDIR=/lib/util/
INFODIR=/images

if grep -q revosavedir /proc/cmdline ;then
    SAVEDIR=`sed -e "s/.*revosavedir=\([^ ]*\).*/\1/" < /proc/cmdline`
fi

RPCINFO=`rpcinfo -p $SIP`

logger "rpcinfo:"
logger "$RPCINFO"

# check nfs
echo
sleep 1
if echo "$RPCINFO" | grep -q nfs
then
    echo "*** NFS seems to be ok on $SIP"
else
    echo "*** Warning : the NFS service does not seem to work on $SIP !"
fi

# get the short mac address
getmac

# NFS base options
NFSOPT="hard,intr,ac,nfsvers=3,async"

# Get NFS proto
if grep -q 'revoproto=nfsudp' /etc/cmdline; then
    NFSOPT="$NFSOPT,proto=udp"
    echo "*** Using NFS over UDP"
else
    if echo "$RPCINFO" | grep nfs | grep -q tcp; then
        NFSOPT="$NFSOPT,proto=tcp"
        echo "*** Using NFS over TCP"
    else
        NFSOPT="$NFSOPT,proto=udp"
        echo "*** Using NFS over UDP"
    fi
fi

# Get NFS block size
if grep -q 'revonfsbsize' /etc/cmdline; then
    NFSBSIZE=`sed -e 's/.*revonfsbsize=\([^ ]*\).*/\1/' < /etc/cmdline`
    NFSOPT="$NFSOPT,rsize=$NFSBSIZE,wsize=$NFSBSIZE"
    echo "*** Using blocks of $NFSBSIZE bytes"
else
    echo "*** Autonegociating block size"
fi

# Full NFS bypass, if needed
if grep -q 'revonfsopts' /etc/cmdline; then
    NFSOPT=`sed -e 's/.*revonfsopts=\([^ ]*\).*/\1/' < /etc/cmdline`
    echo "*** Bypassing NFS options : $NFSOPT"
fi

if [ -z "$Option_177" ]
then
    echo "Using $SIP:$PREFIX as binaries dir"
    mount -t nfs $SIP:$PREFIX$OPTDIR /opt -o hard,intr,nolock,$NFSOPT
    mount -t nfs $SIP:$PREFIX$INFODIR /revoinfo -o hard,intr,nolock,$NFSOPT
    [ -z $SAVEDIR ] || mount -t nfs $SIP:$PREFIX$SAVEDIR /revosave -o hard,intr,nolock,$NFSOPT
else
    echo "Using Option 177: $Option_177 as binaries dir"
    mount -t nfs $Option_177$OPTDIR /opt -o hard,intr,nolock,$NFSOPT
    mount -t nfs $Option_177$INFODIR /revoinfo -o hard,intr,nolock,$NFSOPT
    [ -z $SAVEDIR ] || mount -t nfs $Option_177$SAVEDIR /revosave -o hard,intr,nolock,$NFSOPT
fi
# IMPORTANT !!! NO OTHER INSTRUCTIONS AFTER MOUNTS !!!
