#!/bin/sh

. /usr/lib/revolib.sh

lrs && pretty_orange "Mandriva LRS Client\n" || pretty_orange "Mandriva Pulse 2 Imaging Client\n" 
pretty_orange "`cat /proc/version | cut -f -3 -d \ `"

# disable console blank
echo -e "\033[9;0]"
