#!/bin/sh
#
# (c) 2003-2007 Linbox FAS, http://linbox.com
# (c) 2008-2010 Mandriva, http://www.mandriva.com
#
# $Id$
#
# This file is part of Pulse 2, http://pulse2.mandriva.org
#
# Pulse 2 is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# Pulse 2 is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Pulse 2; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA 02110-1301, USA.
#
ETH=`cat /etc/eth`
MAC=`cat /etc/mac`

. /etc/netinfo.sh
SRV=$Next_server
[ -z "$SRV" ] && exit 1

if [ "$1" = "2" -o "$1" = "3" -o "$1" = "4" -o "$1" = "5" ]
then
    # Also log the image name

    # try to get the image UUID (Pulse 2 mode)
    N=`cat /etc/IMAGE_UUID`

    if [ -z "$N" ]; then # failed => LRS mode
	N=`sed -e 's/.*revosavedir=\([^ ]*\).*/\1/' </etc/cmdline`
	N=`basename $N`
    fi

    echo -en "L${1}-${N}\0Mc:$MAC" | nc -p 1001 -w 1 $SRV 1001
else
    echo -en "L$1Mc:$MAC" | nc -p 1001 -w 1 $SRV 1001
fi
